name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run unit tests
      run: mvn test
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: target/surefire-reports/

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli
      - name: start the back-end
        run: docker-compose up -d
        working-directory: ./
      - name: Run integration tests with Bruno
        run: bru run
        working-directory: test/Voitures
      - name: Archive integration test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: ./target/bruno-reports/
