name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run unit tests
      run: mvn test
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: target/surefire-reports/

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install
      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli
        working-directory: ./
      - name: Run integration tests with Bruno
        run: bru run
        working-directory: test/Voitures
      - name: Run integration tests with Bruno
        run: bru run --output-file bruno.json
        working-directory: test/Voitures

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: ${{ github.workspace }}/test/Voitures/bruno.json